apiVersion: apps/v1
kind: Deployment
metadata: 
  name: todo-backend
  labels:
    app: todo-backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: todo-backend
  template:
    metadata:
      labels:
        app: todo-backend
    annotations:
      prometheus.io/scrape: "true"
      prometheus.io/port: "5000"
      prometheus.io/path: "/metrics"
    spec:
      containers:
        - name: todo-backend
          image: 292578125952.dkr.ecr.ap-south-1.amazonaws.com/todo-app-backend
          ports:
            - containerPort: 5000
          env:
            - name: PGHOST
              value: "todo-app-db.cbym6qeguqg4.ap-south-1.rds.amazonaws.com"
            - name: PGDATABASE
              value: "TodoAppDb"
            - name: PGPORT
              value: "5432"
            - name: PGPASSWORD
              valueFrom:
                secretKeyRef:
                  name: db-credentials
                  key: password 
            - name: PGUSER
              valueFrom: 
                secretKeyRef:
                  name: db-credentials
                  key: username
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "500m"
              memory: "256Mi"

