apiVersion: v1
kind: Service
metadata:
  name: todo-backend
  labels:
    app: todo-backend
  annotations:
    alb.ingress.kubernetes.io/healthcheck-path: /health
spec:
  selector:
      app: todo-backend
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 5000